<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaypalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalInfoRepository extends EntityRepository
{
}
