shop_reservation_precommande:
    path:     /commande/{id_commande}/paiement
    defaults: { _controller: ShopBundle:Reservation:precommande }

shop_precommande_annulation:
    path:     /reservation/annulation/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommandeAnnulation }

shop_ipn_notification:
    path:     /paypal/ipn
    defaults: { _controller: ShopBundle:Paiement:IpnNotification }

shop_precommande_valide:
    path:     /reservation/success
    defaults: { _controller: ShopBundle:Reservation:precommandeValidation }

show_commande:
    path:     /rackel
    defaults: { _controller: ShopBundle:Admin:rackel }

shop_step_2_message:
    path:     /commande/{id_commande}/message
    defaults: { _controller: ShopBundle:Reservation:message }
