shop_reservation_precommande:
    path:     /precommande/paiement/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommande }

shop_reservation_commande:
    path:     /commande/paiement/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommande }

shop_step_2_message:
    path:     /commande/message/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:message }


shop_commande_step_1:
    path:     /commandes/nouvelle
    defaults: { _controller: ShopBundle:CommandeStep:stepOne }

shop_commande_step_2:
    path:     /commandes/message/{id_commande}
    defaults: { _controller: ShopBundle:CommandeStep:stepTwo }

shop_commande_step_3:
    path:     /commandes/paiement/{id_commande}
    defaults: { _controller: ShopBundle:CommandeStep:stepThree }

shop_commande_validee:
    path:     /commandes/paiement/validee/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:validee }

shop_commande_annulee:
    path:     /commandes/paiement/annulee/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:annulee }

shop_commande_paylug:
    path:     /commandes/paiement/payplug/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:payplugIPN }




shop_precommande_annulation:
    path:     /reservation/annulation/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommandeAnnulation }

shop_ipn_notification:
    path:     /paypal/ipn
    defaults: { _controller: ShopBundle:Paiement:IpnNotification }

shop_precommande_valide:
    path:     /reservation/success
    defaults: { _controller: ShopBundle:Reservation:precommandeValidation }

show_commande:
    path:     /rackel
    defaults: { _controller: ShopBundle:Admin:rackel }