shop_reservation:
    path:     /reservation/email/{email}/reservation/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommande }

shop_precommande_annulation:
    path:     /reservation/annulation/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommandeAnnulation }

shop_ipn_notification:
    path:     /paypal/ipn
    defaults: { _controller: ShopBundle:Paiement:IpnNotification }

shop_precommande_valide:
    path:     /reservation/success/{id_commande}
    defaults: { _controller: ShopBundle:Reservation:precommandeValidation }