# Etape 1 : mail et code postal
shop_commande_step_1:
    path:     /commande/nouvelle
    defaults: { _controller: ShopBundle:CommandeStep:stepOne }
# Etape 2 : Message
shop_commande_step_2:
    path:     /commande/message/{id_commande}
    defaults: { _controller: ShopBundle:CommandeStep:stepTwo }
# Etape 3 : Recapitulatif
shop_commande_step_3:
    path:     /commande/paiement/{id_commande}
    defaults: { _controller: ShopBundle:CommandeStep:stepThree }

# Commande validée -> redirection
shop_commande_validee:
    path:     /commande/paiement/validee/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:validee }
# Commande annulée -> redirection
shop_commande_annulee:
    path:     /commande/paiement/annulee/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:annulee }
# Notification IPN PayPlug
shop_commande_paylug:
    path:     /commande/paiement/payplug/{id_commande}
    defaults: { _controller: ShopBundle:Paiement:payplugIPN }
# Notification IPN PayPal
shop_ipn_notification:
    path:     /paypal/ipn
    defaults: { _controller: ShopBundle:Paiement:IpnNotification }

show_commande:
    path:     /rackel
    defaults: { _controller: ShopBundle:Admin:rackel }